backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/images
public_folder: images
# Uncomment local_backend when you need to develop in your local
local_backend: false # run npx netlify-cms-proxy-server for local testing
collections:
  - name: "pages"
    label: "Sivut"
    files:
    - label: "Etusivu"
      name: "home"
      file: "content/home.json"
      fields:
        - label: "Herokuva"
          name: "Hero"
          widget: object
          fields:
            - { label: "Otsikko", name: "HeroTitle", widget: "string", required: false}
            - { label: "Alaotsikko", name: "HeroSubtitle", widget: "string", required: false}
            - { label: "Pöytäkoneen Herokuva", name: "HeroImage", widget: "string", required: false}
            - { label: "Toimintakehotteen teksti", name: "CTAText", widget: "string", required: false}
            - { label: "Linkki", name: "CTALink", widget: "string", required: false}
            - { label: "Näytetäänkö Vaalinumero?", name: "DisplayElectionNumber", widget: "boolean", required: false}
            - { label: "Vaalinumero", name: "ElectionNumber", widget: "string", required: false}
        - label: 'Teemat-osio'
          name: "ThemeSection"
          widget: object
          fields:
          - { label: "Osion otsikko", name: "SectionTitle", widget: "string", required: false }  
          - label: "Teemat"
            name: "themes"
            widget: list
            required: false
            fields:
              - { label: "Teeman otsikko", name: "title", widget: "string", required: false}
              - { label: "Kuvaus", name: "description", widget: "text", required: false}
              - { label: "Kuva", name: "image", widget: "image", required: false}
        - label: "Referenssit-osio"
          name: "ReferenceSection"
          widget: object
          required: false
          fields:
          - { label: "Osion otsikko", name: "SectionTitle", widget: "string", required: false }  
          - label: "Referenssit"
            name: "referees"
            widget: list
            required: false
            fields:
              - { label: "Referoija", name: "referee", widget: "string", required: false}
              - { label: "Referoijan nimike", name: "refereeTitle", widget: "string", required: false}
              - { label: "Referenssi", name: "reference", widget: "text", required: false}
              - { label: "Kuva", name: "image", widget: "image", required: false}
        - label: "Sivuston metatiedot"
          name: "meta"
          widget: object
          required: false
          fields:
          - { label: "Sivun otsikko", name: "title", widget: "string", required: false}
          - { label: "Sivun kuvaus", name: "description", widget: "Vahvan talouden Turku", required: false}
          - { label: "Sivun linkki", name: "url", widget: "string", required: false}
          - { label: "Sivun kuva", name: "image", widget: "image", required: false}
    - label: "Vaaliteemat"
      name: "themes"
      file: content/themes.json
      fields:
        - label: "Herokuva"
          name: "Hero"
          widget: object
          required: false
          fields:
            - { label: "Otsikko", name: "HeroTitle", widget: "string", required: false}
            - { label: "Alaotsikko", name: "HeroSubtitle", widget: "string", required: false}
            - { label: "Pöytäkoneen Herokuva", name: "HeroImage", widget: "image", required: false}
        - label: 'Teemat-osio'
          name: "ThemeSection"
          widget: object
          required: false
          fields:
          - label: "Teemat"
            name: "themes"
            widget: list
            required: false
            fields:
              - { label: "Teeman otsikko", name: "title", widget: "string", required: false}
              - { label: "Kuvaus", name: "description", widget: "text", required: false}
              - { label: "Kuva", name: "image", widget: "image", required: false}
    - label: "Koli"
      name: "aboutMe"
      file: "content/aboutMe.json"
      fields:
        - label: "Herokuva"
          name: "Hero"
          widget: object
          required: false
          fields:
            - { label: "Otsikko", name: "HeroTitle", widget: "string", required: false}
            - { label: "Alaotsikko", name: "HeroSubtitle", widget: "string", required: false}
            - { label: "Pöytäkoneen Herokuva", name: "HeroImage", widget: "image"}
        - label: "Usein kysytyt kysymykset"
          name: "FAQSection"
          widget: object
          required: false
          fields:
            - { label: "Pöytäkoneen Profiilikuva", name: "faqProfilePicture", widget: "image"}
            - { label: "Profiilikuva selvennys", name: "faqProfilePictureAlt", widget: "string", required: false}
            - label: "Kysymykset"
              name: "faqs"
              widget: list
              required: false
              fields:
                - { label: "Kysymys", name: "question", widget: "string", required: false}
                - { label: "Vastaus", name: "answer", widget: "text", required: false}
                - { label: "Vastaus näkyvissä?", name: "open", widget: "boolean", required: false}
    - label: "Yhteydenotto"
      name: "contact"
      file: "content/contact.json"
      fields:
        - label: "Yhteydenotto"
          name: "ContactSection"
          widget: object
          required: false
          fields: 
            - { label: "Otsikko", name: "title", widget: "string", required: false}
            - { label: "Kuvaus", name: "description", widget: "text"}
            - { label: "Lomakkeen painike", name: "button", widget: "text"}
  - name: "general"
    label: "Sivun asetukset"
    files:
    - label: "Yleiset osiot"
      name: "site"
      file: "content/site.json"
      fields:
        - label: "Yläpalkki"
          name: "Navigation"
          widget: object
          fields:
           - { label: "Logo", name: "logo", widget: "string", required: false}
           - { label: "Mobiili Kokoomuslogo", name: "mobileImageLogo", widget: "image", required: false}
           - { label: "Mobiiliu Kokoomuslogon täsmennys", name: "mobileImageAlt", widget: "string", required: false}
           - { label: "Etusivu", name: "homeTitle", widget: "string", default: "Etusivu", required: false}
           - { label: "Vaaliteemat", name: "themesTitle", default: "Vaaliteemat", widget: "string", required: false}
           - { label: "Juho", name: "aboutMeTitle", default: "Juho",  widget: "string", required: false}
           - { label: "Ota Yhteyttä", name: "contactTitle", default: "Ota yhteyttä", widget: "string", required: false}
        - label: "Uutiskirje"
          name: "newsletter"
          widget: object
          required: false
          fields:
          - { label: "Logo", name: "logo", widget: "image", required: false}
          - { label: "Otsikko", name: "title", widget: "string", required: false}
          - { label: "kuvaus", name: "description", widget: "string", required: false}
          - { label: "Toimintakehotteen teksti", name: "cta", widget: "string", required: false}
          - { label: "Taustakuva", name: "backgroundImage", widget: "image", required: false}
        - label: "Alapalkki"
          name: "Footer"
          widget: object
          fields:
           - { label: "Pöytäkoneen Kokoomuslogo", name: "desktopLogoImage", widget: "image", required: false}
           - { label: "Kokoomuslogon täsmennys", name: "desktopLogoAlt", widget: "string", required: false}
           -   label: "Sosiaalinen Media"
               name: "socialMedia"
               widget: list
               collapsed: true
               required: false
               hint: "Täällä voit lisätä somesi, Klikkaa 'Add social icons'"
               fields:
                - label: "Icons"
                  name: "icon"
                  widget: "select"
                  options:
                    [
                      "Twitter",
                      "LinkedIn",
                      "Instagram",
                      "Email",
                      "Phone",
                      "Whatsapp",
                      "Facebook",
                    ]
                  hint: "Valitse ikoni"
                - widget: string
                  name: url
                  label: url
                  hint: "Laita tähän URL:i SoMe kanavaasi"
                - widget: string
                  name: description
                  label: description
                  hint: "Laita tähän kuvaus kanavastasi. Esim käyttäjänimike."